apiVersion: v1
kind: Pod
metadata:
  name: hl-smi
spec:
  hostNetwork: true
  containers:
  - name: app
    image: artifactory.habana-labs.com/docker-developers/base/u18/u18-base:bionic-20190307
    command: ["/bin/bash"]
    args: ["-c", "hl-smi"]
    resources:
      limits:
        habana.ai/gaudi: 1
    volumeMounts:
    - name: usr
      mountPath: /usr/bin
  volumes:
  - name: usr
    hostPath:
      path: /usr/bin
