apiVersion: v1
kind: Pod
metadata:
  name: hl-smi
spec:
  containers:
  - name: app
    image: vault.habana.ai/gaudi-docker/1.16.0/ubuntu22.04/habanalabs/pytorch-installer-2.2.2:1.16.0-526
    command: ["/bin/bash"]
    args: ["-c", "hl-smi"]
    resources:
      limits:
        habana.ai/gaudi: 1
